
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class breeder
{

    public int slno { get; set; }

    public string breedername { get; set; }

    public string address { get; set; }

    public string contactno { get; set; }

    public string emailid { get; set; }

    public int addby { get; set; }

}

}
