//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cock
    {
        public int slno { get; set; }
        public string cock_name { get; set; }
        public int cock_weight { get; set; }
        public int breeder_slno { get; set; }
        public string breed { get; set; }
        public string age { get; set; }
        public string image { get; set; }
        public int type { get; set; }
        public string cocktype { get; set; }
        public int addby { get; set; }
    }
}
