
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class comm_calculation
{

    public int slno { get; set; }

    public int playerid { get; set; }

    public int firstparent_id { get; set; }

    public float firstparent_bet_comm { get; set; }

    public float firstparent_win_comm { get; set; }

    public int secondparent_id { get; set; }

    public float secondparent_bet_comm { get; set; }

    public float secondparent_win_comm { get; set; }

    public int thirdparent_id { get; set; }

    public float thirdparent_bet_comm { get; set; }

    public float thirdparent_win_comm { get; set; }

    public int fourth_id { get; set; }

    public float fourthparent_bet_comm { get; set; }

    public float fourthparent_win_comm { get; set; }

    public int admin_id { get; set; }

    public float admin_bet_comm { get; set; }

    public float admin_win_comm { get; set; }

    public int delflag { get; set; }

}

}
