//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency_exchange
    {
        public int slno { get; set; }
        public System.DateTime date { get; set; }
        public string currency { get; set; }
        public float val { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
