//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class fight_back
    {
        public int slno { get; set; }
        public int matchno { get; set; }
        public string type { get; set; }
        public int player_id { get; set; }
        public float amt_player { get; set; }
        public string odds { get; set; }
        public int agent_id { get; set; }
        public float amt_agent { get; set; }
        public float agent_per { get; set; }
        public int transaction_slno { get; set; }
        public System.DateTime date { get; set; }
        public int delflag { get; set; }
    }
}
