//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public int id { get; set; }
        public string name { get; set; }
        public string en { get; set; }
        public string ch { get; set; }
        public string bh { get; set; }
        public string vt { get; set; }
        public string th { get; set; }
    }
}
