//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class marketvalue
    {
        public int id { get; set; }
        public int playerid { get; set; }
        public int matchno { get; set; }
        public float marketvalue1 { get; set; }
        public string type { get; set; }
        public float bet_eat_value { get; set; }
        public string bet_eat { get; set; }
        public float avail_bet { get; set; }
        public float avail_eat { get; set; }
        public int bet_slno { get; set; }
        public int eat_slno { get; set; }
    }
}
