//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class match_createstart
    {
        public int slno { get; set; }
        public System.DateTime create_date { get; set; }
        public string time { get; set; }
        public int arenaid { get; set; }
        public int fighttype { get; set; }
        public string description { get; set; }
        public System.DateTime enddate { get; set; }
        public string endtime { get; set; }
        public int cancel_status { get; set; }
    }
}
