
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class matchstarttime
{

    public int id { get; set; }

    public int matchno { get; set; }

    public string starttime { get; set; }

    public string stoptime { get; set; }

    public string totaltime { get; set; }

}

}
