//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class multiple_transfer
    {
        public int slno { get; set; }
        public int transfer_by { get; set; }
        public int transfer_to { get; set; }
        public float amount { get; set; }
        public System.DateTime date { get; set; }
        public string type { get; set; }
        public int delflag { get; set; }
    }
}
