//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class oddsdiff_calc
    {
        public int idval { get; set; }
        public int match_slno { get; set; }
        public float C1odds { get; set; }
        public float C2odds { get; set; }
        public float diff { get; set; }
    }
}
