//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class oddsdetail
    {
        public int id { get; set; }
        public int matchno { get; set; }
        public float odds_difference { get; set; }
        public float openingodds_meron { get; set; }
        public float openingodds_wala { get; set; }
        public float oddsadjustment_value { get; set; }
        public float oddsbet_threshold { get; set; }
        public float maxbet_threshold { get; set; }
        public System.DateTime time { get; set; }
    }
}
