//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class playerbetlimnit_nouse
    {
        public int id { get; set; }
        public int playerid { get; set; }
        public double minbet_meron { get; set; }
        public double maxbet_meron { get; set; }
        public double meronbet_permatch { get; set; }
        public double minbet_wala { get; set; }
        public double maxbet_wala { get; set; }
        public double walabet_permatch { get; set; }
        public double minbet_draw { get; set; }
        public double maxbet_draw { get; set; }
        public double drawbet_permatch { get; set; }
        public int currency { get; set; }
    }
}
