
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class player_pt_calc
{

    public int id { get; set; }

    public int player_id { get; set; }

    public float firstparent { get; set; }

    public int firstparent_id { get; set; }

    public float secondparent { get; set; }

    public int secondparent_id { get; set; }

    public float thirdparent { get; set; }

    public int thirdparent_id { get; set; }

    public float fourthparent { get; set; }

    public int fourthparent_id { get; set; }

    public float frstparentcomm { get; set; }

    public float secondparentcomm { get; set; }

    public float thirdparentcomm { get; set; }

    public float fourthparentcomm { get; set; }

    public float admincomm { get; set; }

    public int del_flag { get; set; }

    public System.DateTime updated_time { get; set; }

}

}
