
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class request_point
{

    public int id { get; set; }

    public int from { get; set; }

    public int to { get; set; }

    public float point { get; set; }

    public int status { get; set; }

    public System.DateTime date { get; set; }

}

}
