//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class s_dbEntities : DbContext
    {
        public s_dbEntities()
            : base("name=s_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<agentbet_limit> agentbet_limit { get; set; }
        public DbSet<agentbet_limit_backup> agentbet_limit_backup { get; set; }
        public DbSet<allbetcomm> allbetcomms { get; set; }
        public DbSet<allwincomm> allwincomms { get; set; }
        public DbSet<announcement> announcements { get; set; }
        public DbSet<arena> arenas { get; set; }
        public DbSet<bidpoint> bidpoints { get; set; }
        public DbSet<breeder> breeders { get; set; }
        public DbSet<cock> cocks { get; set; }
        public DbSet<comm_calculation> comm_calculation { get; set; }
        public DbSet<commission> commissions { get; set; }
        public DbSet<country_currency> country_currency { get; set; }
        public DbSet<creaditbalance> creaditbalances { get; set; }
        public DbSet<currency> currencies { get; set; }
        public DbSet<currency_exchange> currency_exchange { get; set; }
        public DbSet<derby> derbies { get; set; }
        public DbSet<drawodd> drawodds { get; set; }
        public DbSet<fight_assign> fight_assign { get; set; }
        public DbSet<fight_back> fight_back { get; set; }
        public DbSet<language> languages { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<marketvalue> marketvalues { get; set; }
        public DbSet<match_createstart> match_createstart { get; set; }
        public DbSet<matchending_announcement> matchending_announcement { get; set; }
        public DbSet<matchstarttime> matchstarttimes { get; set; }
        public DbSet<multiple_transfer> multiple_transfer { get; set; }
        public DbSet<mwval> mwvals { get; set; }
        public DbSet<oddsdetail> oddsdetails { get; set; }
        public DbSet<oddsdiff_calc> oddsdiff_calc { get; set; }
        public DbSet<openning_balance> openning_balance { get; set; }
        public DbSet<player_pt_calc> player_pt_calc { get; set; }
        public DbSet<playerbet_commission> playerbet_commission { get; set; }
        public DbSet<playerbet_limit> playerbet_limit { get; set; }
        public DbSet<playerbet_limit_backup> playerbet_limit_backup { get; set; }
        public DbSet<playerbetcomm> playerbetcomms { get; set; }
        public DbSet<request_point> request_point { get; set; }
        public DbSet<running_announcement> running_announcement { get; set; }
        public DbSet<senior_commission> senior_commission { get; set; }
        public DbSet<stake_detail> stake_detail { get; set; }
        public DbSet<test> tests { get; set; }
        public DbSet<transaction> transactions { get; set; }
        public DbSet<typeof_currency> typeof_currency { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<playerbetlimnit_nouse> playerbetlimnit_nouse { get; set; }
        public DbSet<u2> u2 { get; set; }
        public DbSet<view_cocktype> view_cocktype { get; set; }
        public DbSet<view_downline> view_downline { get; set; }
        public DbSet<view_fightback> view_fightback { get; set; }
        public DbSet<view_fullcomm> view_fullcomm { get; set; }
        public DbSet<view_matchdetail> view_matchdetail { get; set; }
        public DbSet<view_odds> view_odds { get; set; }
        public DbSet<view_playerbetreport> view_playerbetreport { get; set; }
        public DbSet<view_playercomm> view_playercomm { get; set; }
        public DbSet<view_playeruplines> view_playeruplines { get; set; }
    }
}
