
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class senior_commission
{

    public int slno { get; set; }

    public int agent_id { get; set; }

    public int down_id { get; set; }

    public float betcom { get; set; }

    public float wincom { get; set; }

}

}
