
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class stake_detail
{

    public int id { get; set; }

    public float fightback { get; set; }

    public float bet_comm { get; set; }

    public float win_comm { get; set; }

    public System.DateTime date { get; set; }

}

}
