
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class u2
{

    public int slno { get; set; }

    public string name { get; set; }

    public string lname { get; set; }

    public string preffix { get; set; }

    public string idval { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string address { get; set; }

    public string contactno { get; set; }

    public string emailid { get; set; }

    public string country { get; set; }

    public string pinno { get; set; }

    public int status { get; set; }

    public System.DateTime date { get; set; }

    public int agent_id { get; set; }

    public string type { get; set; }

    public float maxfightback { get; set; }

    public float parentfightback { get; set; }

    public int arena { get; set; }

    public string currency_type { get; set; }

    public float draw_fightback { get; set; }

    public System.DateTime reset_date { get; set; }

    public string ip_address { get; set; }

    public int user_status { get; set; }

    public int online_status { get; set; }

    public int show_status { get; set; }

    public string unique_idval { get; set; }

    public System.DateTime last_ac_time { get; set; }

    public string last_edit_time { get; set; }

}

}
