
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class view_playeruplines
{

    public int Player { get; set; }

    public int agent { get; set; }

    public int master { get; set; }

    public int srmaster { get; set; }

    public int house { get; set; }

    public string stakeholder { get; set; }

    public string Playername { get; set; }

    public string currency { get; set; }

}

}
