//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_playerbetreport
    {
        public int matchno { get; set; }
        public string cocktype { get; set; }
        public float acceptedamount { get; set; }
        public string odds { get; set; }
        public double winloseamnt { get; set; }
        public string winner { get; set; }
        public string gain { get; set; }
        public System.DateTime date { get; set; }
    }
}
