
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sabong.Repository.EntityModel
{

using System;
    using System.Collections.Generic;
    
public partial class view_matchdetail
{

    public int cid { get; set; }

    public int acid { get; set; }

    public string cock_type { get; set; }

    public string against_type { get; set; }

    public int fslno { get; set; }

    public string fdate { get; set; }

    public int match_no { get; set; }

    public int status { get; set; }

    public int block { get; set; }

    public int cancelmatch { get; set; }

    public int arena { get; set; }

    public int winner_cockid { get; set; }

    public int match_order { get; set; }

    public int cbid { get; set; }

    public int abid { get; set; }

    public string cname { get; set; }

    public string cimage { get; set; }

    public string agname { get; set; }

    public string agimage { get; set; }

    public string cbreedername { get; set; }

    public Nullable<double> C1odds { get; set; }

    public Nullable<double> C2odds { get; set; }

    public string drawwodds { get; set; }

    public string abreedername { get; set; }

    public string winner { get; set; }

    public string ftd { get; set; }

}

}
