//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sabong.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_transactionReport
    {
        public Nullable<long> matchno { get; set; }
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string ip { get; set; }
        public int playerid { get; set; }
        public string odds { get; set; }
        public float acceptedamount { get; set; }
        public string cocktype { get; set; }
        public double winloseamnt { get; set; }
        public string arena { get; set; }
        public string status { get; set; }
        public float betcomamt { get; set; }
        public string breedername { get; set; }
        public string againstbreedername { get; set; }
        public string matchname { get; set; }
    }
}
